apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::536677315951:role/eksctl-eksctl-demo-nodegroup-ng-6-NodeInstanceRole-YP58PM8WOBWZ
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::536677315951:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-03T03:18:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1285"
  uid: b93db398-4477-43be-982a-091306549ff1
