apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::536677315951:role/eksctl-eksctl-demo1-nodegroup-ng-NodeInstanceRole-6IPRWOR4EOHW
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::536677315951:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2023-09-02T11:27:28Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1258"
  uid: 1f2c3503-d3f0-4727-8c61-3eb8091318d8
